#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable

import markdown2

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = PROJECT_ROOT / "reports"
SITE_DIR = PROJECT_ROOT / "site"
OWNER = os.getenv("GITHUB_REPOSITORY_OWNER", "Sham00")
REPO = os.getenv("GITHUB_REPOSITORY", "Sham00/daily_stock_analysis").split("/", 1)[-1]
BRANCH = os.getenv("GITHUB_REF_NAME", "main")
DATE_KEY = datetime.utcnow().strftime("%Y-%m-%d")


@dataclass
class ReportDoc:
    title: str
    path: Path
    body: str
    section: str


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _find_reports() -> list[ReportDoc]:
    docs: list[ReportDoc] = []
    if not REPORTS_DIR.exists():
        return docs

    for path in sorted(REPORTS_DIR.glob("report_*.md"), reverse=True):
        docs.append(ReportDoc(title=f"Daily stock analysis ({path.stem.replace('report_', '')})", path=path, body=_read(path), section="Deep analysis"))
        break

    for path in sorted(REPORTS_DIR.glob("market_review_*.md"), reverse=True):
        docs.append(ReportDoc(title=f"Market review ({path.stem.replace('market_review_', '')})", path=path, body=_read(path), section="Market review"))
        break

    for path in sorted(REPORTS_DIR.glob("trade_tickets_*.md"), reverse=True):
        docs.append(ReportDoc(title=f"Trade tickets ({path.stem.replace('trade_tickets_', '')})", path=path, body=_read(path), section="Trade tickets"))
        break

    return docs


def _html_template(title: str, subtitle: str, sections: Iterable[str], toc: str) -> str:
    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>{title}</title>
  <style>
    :root {{ color-scheme: dark; --bg:#0b1020; --card:#121933; --muted:#95a3c7; --text:#edf2ff; --accent:#7cc4ff; --border:#243056; }}
    body {{ margin:0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, sans-serif; background:linear-gradient(180deg,#0b1020,#0e1530 35%,#11172e); color:var(--text); }}
    .wrap {{ max-width: 1080px; margin: 0 auto; padding: 32px 20px 80px; }}
    .hero {{ margin-bottom: 24px; }}
    h1 {{ font-size: 34px; margin: 0 0 8px; }}
    .subtitle {{ color: var(--muted); font-size: 15px; }}
    .grid {{ display:grid; grid-template-columns: 260px 1fr; gap: 24px; }}
    .card {{ background: rgba(18,25,51,.88); border:1px solid var(--border); border-radius: 18px; box-shadow: 0 14px 36px rgba(0,0,0,.28); }}
    .toc {{ position: sticky; top: 20px; padding: 18px; }}
    .toc h2 {{ font-size: 14px; letter-spacing: .08em; text-transform: uppercase; color: var(--muted); margin: 0 0 12px; }}
    .toc a {{ display:block; color:var(--accent); text-decoration:none; padding: 8px 0; font-size:14px; }}
    .content {{ padding: 22px 26px; }}
    .section {{ margin-bottom: 28px; padding-bottom: 10px; border-bottom: 1px solid rgba(255,255,255,.06); }}
    .section:last-child {{ border-bottom:none; margin-bottom:0; }}
    .section h2 {{ margin: 0 0 14px; font-size: 24px; }}
    .prose h1,.prose h2,.prose h3 {{ color:#fff; }}
    .prose p,.prose li,.prose blockquote {{ color: #d9e2ff; line-height: 1.65; }}
    .prose code {{ background:#0b1020; padding:2px 6px; border-radius:6px; }}
    .prose pre {{ overflow:auto; background:#0a0f1f; padding:14px; border-radius:12px; border:1px solid rgba(255,255,255,.07); }}
    .prose table {{ width:100%; border-collapse: collapse; font-size: 14px; }}
    .prose th,.prose td {{ border:1px solid rgba(255,255,255,.12); padding:8px 10px; vertical-align: top; }}
    .meta {{ margin-top: 18px; color: var(--muted); font-size: 13px; }}
    .pill {{ display:inline-block; background:#172147; border:1px solid #263562; border-radius:999px; padding:6px 10px; margin-right:8px; font-size:12px; color:#c9d6ff; }}
    @media (max-width: 900px) {{ .grid {{ grid-template-columns: 1fr; }} .toc {{ position: static; }} }}
  </style>
</head>
<body>
  <div class=\"wrap\">
    <div class=\"hero\">
      <div class=\"pill\">Daily report</div><div class=\"pill\">Telegram + GitHub Pages</div>
      <h1>{title}</h1>
      <div class=\"subtitle\">{subtitle}</div>
    </div>
    <div class=\"grid\">
      <aside class=\"card toc\">
        <h2>Sections</h2>
        {toc}
      </aside>
      <main class=\"card content\">{''.join(sections)}<div class=\"meta\">Generated by GitHub Actions on branch {BRANCH}.</div></main>
    </div>
  </div>
</body>
</html>"""


def _render_section(doc: ReportDoc, idx: int) -> tuple[str, str]:
    anchor = f"section-{idx}"
    html = markdown2.markdown(doc.body, extras=["fenced-code-blocks", "tables", "strike", "header-ids"])
    section = f"<section id='{anchor}' class='section'><h2>{doc.section}</h2><div class='meta'>{doc.title}</div><div class='prose'>{html}</div></section>"
    toc = f"<a href='#{anchor}'>{doc.section}</a>"
    return section, toc


def main() -> None:
    docs = _find_reports()
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    day_dir = SITE_DIR / "daily" / DATE_KEY
    day_dir.mkdir(parents=True, exist_ok=True)

    sections: list[str] = []
    toc: list[str] = []
    if docs:
        for idx, doc in enumerate(docs, start=1):
            section, toc_link = _render_section(doc, idx)
            sections.append(section)
            toc.append(toc_link)
    else:
        sections.append("<section class='section'><h2>No report generated</h2><div class='prose'><p>No markdown reports were found in <code>reports/</code> for this run.</p></div></section>")
        toc.append("<a href='#'>No report generated</a>")

    title = f"Daily trading report — {DATE_KEY}"
    subtitle = f"Portfolio actions, trade tickets, and Gemini deep analysis for {DATE_KEY}."
    html = _html_template(title, subtitle, sections, "".join(toc))
    (day_dir / "index.html").write_text(html, encoding="utf-8")
    (SITE_DIR / "index.html").write_text(html, encoding="utf-8")

    report_url = f"https://{OWNER.lower()}.github.io/{REPO}/daily/{DATE_KEY}/"
    (SITE_DIR / "report_url.txt").write_text(report_url, encoding="utf-8")
    (SITE_DIR / "manifest.json").write_text(json.dumps({"date": DATE_KEY, "url": report_url}, indent=2), encoding="utf-8")
    print(report_url)


if __name__ == "__main__":
    main()
